/*!

=========================================================
* Paper Kit React - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-kit-react

* Copyright 2019 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/paper-kit-react/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// Header and Footer
import EnglishNavBar from 'components/Navbars/EnglishNavBar';
import EnglishFooterPage from 'components/Footers/EnglishFooterPage';


// reactstrap components

// reactstrap components
import {
    Container,
    Row,
    Col
  } from "reactstrap";

// core components

function Experience() {
  return (
    <>
         <div className="section section-image section-login"
            style={{ backgroundImage: "url(" + require("assets/img/background/bluebg.jpg") + ")" }} > 
            <EnglishNavBar></EnglishNavBar>
            <br /> 
            <div id="images">
                    
                    {/* pictures from the CEO */}
                    <Container className="tim-container">
                        <div id="images">
                            <Container>
                                <div class='title'> 
                                <h2 align="center"><b>Message from our CEO</b></h2>
                                    <h3 className="description" >Dr. Carlos D. Rodríguez Valdez</h3>
                                    </div>
                                    <Row>
                                        <Col className="mr-auto" md="4" sm="6" >
                                            <img
                                            alt="Arturo Parra"
                                            className="img-rounded img-responsive"
                                            src={require("assets/img/ceo/carlosCEO.jpg")}
                                            />
               
                                        </Col>
                                        <Col>
                                        <h4 className="description">Dear APR-control community and friends</h4>
                                        <h4 className="description" align="justify">
                                        As the global pandemic generated by the SARS-CoV-2 virus evolves, please, know that we have taken proactive steps to protect our staff and partners, and the communities where we live and work. We have a team dedicated to our response during this challenging time, and we are taking guidance from the Minister of Health (MINSA), the World Health Organization, and the localities where we work. 
                                        </h4>
                                        <h4 className="description" align="justify">
                                        As the global pandemic generated by the SARS-CoV-2 virus evolves, please, know that we have taken proactive steps to protect our staff and partners, and the communities where we live and work. We have a team dedicated to our response during this challenging time, and we are taking guidance from the Minister of Health (MINSA), the World Health Organization, and the localities where we work.
                                        </h4>
                                        </Col>
                                    </Row>
                            </Container>
                        </div>
                        <br />
                        <h4 className="description" align="justify"> 
                        This is a very difficult and uncertain time for everyone, but we are not losing sight of the importance of our work. We remain committed to helping our community build back better and stronger; and we remain dedicated to our mission of ensuring a clean, prosperous future for the world. We hope you and yours are staying healthy, and we look forward to better times for our continued work together.
                        </h4>
                        <br />
                        <br />
                        <Row>
                            <Col className="mr-auto" md="4" sm="6">
                                            <img
                                            alt="..."
                                            className="img-rounded img-responsive"
                                            src={require("assets/img/ceo/signature.jpg")}
                                            />
               
                                        </Col>
                                    </Row>
                                    <br />
                                    <h4 className="description"> Lima, October 18th, 2020</h4>
                        
                    </Container>
                    <br />
                    {/* End pictures from the CEO */}
                </div>
            </div>
    <EnglishFooterPage></EnglishFooterPage>
    </>
  );
}

export default Experience;
